### ISSUE TITLE
csv is not really csv here

### ISSUE THREAD

**Issue by akshaybabloo** [philipperemy/FX-1-Minute-Data#2]
Thanks for the dataset, but shouldn't there be `,` instead of `;` in the CSV files?

**Comment by philipperemy** [comment]
@akshaybabloo yes makes sense. I didn't generate those CSV. They are directly downloaded from histdata.com. I'm going to add a note in the README

**Comment by philipperemy** [comment]
@akshaybabloo yes makes sense. I didn't generate those CSV. They are directly downloaded from histdata.com. I'm going to add a note in the README
